config/routes.rb
Rails.application.routes.draw do
  # 顧客用
# URL /users/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 # ゲストログイン
devise_scope :user do
      post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
                  end

namespace :admin do
    root to: "homes#top"
    resources :users
    resources :grants do
    resources :grant_comments, only: [:destroy]
   end
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
   end

 scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
      resources :users do
        collection do
          # 退会確認画面
          get  '/users/check' => 'users#check'
          # 論理削除用のルーティング
          patch  '/users/withdraw' => 'users#withdraw'
        end
      end
    resources :grants do
    resources :grant_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :grants, dependent: :destroy

validates :name, presence: true

  def self.looks(search, word)
    if search == "perfect_match"
      @tag = Tag.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @tag = Tag.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @tag = Tag.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @tag = Tag.where("name LIKE?","%#{word}%")
    else
      @tag = Tag.all
    end
  end

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
before_action :authenticate_admin!
before_action :load_tags, only: [:index, :create, :update]
  def index
    @tags = Tag.all
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
       @tags = Tag.all
       render :index
    else
       @tags = Tag.all
        redirect_to admin_tags_path, alert: "登録に失敗しました。"
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to admin_tags_path, notice: "削除しました。"
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

  def load_tags
    @tags = Tag.all
  end

end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 mx-auto">
      <h3 class="ml-5 my-5">タグ編集</h3>
      <div class="form-group">
        <%= form_with model: @tag, url: admin_tag_path do |f| %>
          <div class="form-group">
            <%= f.label "タグ名" %>
            <%= f.text_field :name, id: "inputname", class: "form-control" %>
          </div>
          <%= f.submit "変更を保存", class: "btn btn-custom-color my-3 mr-3" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

<style>
  .btn-custom-color {
    background-color: #007bff; /* 青色 */
    border: 2px solid #3498db; /* 枠線を付ける */
    color: #ffffff; /* 白色のテキスト */
  }

  .btn-custom-color:hover {
    background-color: #2980b9; /* ホバー時の色 */
    border-color: #2980b9; /* ホバー時の枠線色 */
  }
</style>

app/views/admin/tags/index.html.erb
<%= form_with model: @tag, url: admin_tags_path do |f| %>
  <%= f.label "タグ名" %>
  <%= f.text_field :name %>
  <%= f.submit "新規登録", class: "btn btn-custom-color" %>
<% end %>

<table class="table mt-5 w-50" style="color: white;">
  <thead style="background-color: #d3d3d3; text-align: center;">
    <tr>
      <th style="color: black;">タグ</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to "編集する", edit_admin_tag_path(tag), class: "btn btn-custom-color py-0 " %></td>
        <td><%= link_to "削除", admin_tag_path(tag), method: :delete, class: "btn btn-custom-color py-0", "data-confirm" => "本当に削除しますか？" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<style>
  .btn-custom-color {
    background-color: #007bff;
    border: 2px solid #3498db;
    color: #ffffff;
  }

  .btn-custom-color:hover {
    background-color: #2980b9;
    border-color: #2980b9;
  }
</style>