config/routes.rb
Rails.application.routes.draw do
  # 顧客用
# URL /users/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 # ゲストログイン
devise_scope :user do
      post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
                  end

namespace :admin do
    root to: "homes#top"
    resources :users
    resources :grants do
    resources :grant_comments, only: [:destroy]
   end
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
   end

 scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
      resources :users do
        collection do
          # 退会確認画面
          get  '/users/check' => 'users#check'
          # 論理削除用のルーティング
          patch  '/users/withdraw' => 'users#withdraw'
        end
      end
    resources :grants do
    resources :grant_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  end
end

app/models/grant.rb
class Grant < ApplicationRecord
  belongs_to :user
  belongs_to :tag

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :grant_comments, dependent: :destroy
  has_many :grant_tags, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true
  validates :background, presence: true
  validates :body, presence: true

def favorited_by?(user)
  user.present? && favorites.exists?(user_id: user.id)
end

  # メソッド名をself.searchと変更
  def self.looks(search, word)
    if search == "perfect_match"
      where("name LIKE ?", "#{word}")
    elsif search == "forward_match"
      where("name LIKE ?", "#{word}%")
    elsif search == "backward_match"
      where("name LIKE ?", "%#{word}")
    elsif search == "partial_match"
      where("name LIKE ?", "%#{word}%")
    else
      all
    end
  end

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.days.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.weeks.ago.beginning_of_day..1.week.ago.end_of_day) }
  scope :created_two_weeks_ago, -> { where(created_at: (2.weeks.ago.beginning_of_day)..(2.weeks.ago.end_of_day)) }
end

app/controllers/admin/grants_controller.rb
class Admin::GrantsController < ApplicationController
before_action :authenticate_admin!

  def index
   @tags = Tag.all
   @grants = Grant.page(params[:page])
   @grant_comment = GrantComment.page(params[:page])
   @today_grant = @grants.where("created_at >= ?", Date.today.beginning_of_day).count
   @yesterday_grant = @grants.where("created_at >= ? AND created_at < ?", Date.yesterday.beginning_of_day, Date.today.beginning_of_day).count
   @this_week_grant = @grants.where("created_at >= ?", Date.today.beginning_of_week).count
   @last_week_grant = @grants.where("created_at >= ? AND created_at < ?", Date.today.beginning_of_week - 7.days, Date.today.beginning_of_week).count
   @two_weeks_ago_grant = @grants.where("created_at >= ? AND created_at < ?", Date.today.beginning_of_week - 14.days, Date.today.beginning_of_week - 7.days).count
  end

  def show
    @grant = Grant.find(params[:id])
    @grant_comment = GrantComment.all
    @tag = @grant.tag if @grant.tag.present?
  end

   def destroy
    @grant = Grant.find(params[:id])
    @grant.destroy
    redirect_to admin_grants_path, notice: "削除しました。"
   end
end

app/helpers/admin/grants_helper.rb
module Admin::GrantsHelper
end

app/views/admin/grants/_index.html.erb
<div class="container text-center" style="background-color: #f0f6fa; padding: 20px;">
 <h4 style="color: black;">投稿数の前日比・前週比</h4>
<div class="table_width">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th style="color: black;">今日の投稿</th>
        <th style="color: black;">昨日の投稿</th>
        <th style="color: black;">前日比</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="color: black;"><%= @today_grant %></td>
        <td style="color: black;"><%= @yesterday_grant %></td>
        <% if @yesterday_grant == 0 %>
          <td style="color: black;">前日の投稿はなし</td>
        <% else %>
          <td style="color: black;">
            <% @the_day_before = @today_grant / @yesterday_grant %>
            <%= (@the_day_before * 100).round %>%
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th style="color: black;">今週の投稿</th>
        <th style="color: black;">先週の投稿</th>
        <th style="color: black;">先週比</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="color: black;"><%= @this_week_grant %></td>
        <td style="color: black;"><%= @last_week_grant %></td>
        <% if @last_week_grant == 0 %>
          <td style="color: black;">先週の投稿はなし</td>
        <% else %>
          <td style="color: black;">
           <% @the_week_before = @this_week_grant / @last_week_grant %>
              <%= number_with_precision(@the_week_before * 100, precision: 2) %>%
          </td>
        <% end %>
      </tr>
    </tbody>
    </table>
    <title>週ごとの投稿数</title>
<canvas id="weekly-post-chart" width="400" height="200"></canvas>
</div>
<script>
  // グラフデータをJavaScript変数に保存
  var chartData = {
    labels: ["先々週", "先週", "今週"], // 週ごとのラベル
    datasets: [{
      label: "週ごとの投稿数",
      data: [<%= @two_weeks_ago_grant %>, <%= @last_week_grant %>, <%= @this_week_grant %>], // 週ごとのデータ
      backgroundColor: "rgba(75, 192, 192, 0.2)",
      borderColor: "rgba(75, 192, 192, 1)",
      borderWidth: 1
    }]
  };

  // グラフを描画する関数
  function renderChart() {
    var ctx = document.getElementById('weekly-post-chart').getContext('2d');
    var chart = new Chart(ctx, {
      type: 'bar', // 折れ線グラフにする場合は 'line' に変更
      data: chartData,
      options: {
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true
            }
          }]
        }
      }
    });
  }

  // ページが読み込まれたときにグラフを描画
  window.onload = renderChart;
</script>

  </div>

app/views/admin/grants/index.html.erb
   <!-- Chart.jsをCDNから読み込む -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div class="container text-center" style="background-color: #f0f6fa; padding: 20px;">
  　<h1 class="py-5" style="color: #3498db;">投稿一覧</h1>

  <div class="row justify-content-center">
    <div class="dropdown col-lg-3">
      <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <% @tags.each do |tag| %>
        <li>
          <a><%= link_to tag.name, grants_path(tag_id: tag.id), class: "text-decoration-none text-dark rounded p-2", style: "background-color: #d1d8e0;" %></a>
        </li>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container my-3">
    <div class="row">
      <% @grants.each do |grant| %>
        <div class="card-group col-lg-4">
          <div class="card my-3" style="border-color: #3498db;">
            <div class="card-body">
              <div class="card-title">
                <%= link_to grant.name, admin_grant_path(grant), class: "text-dark", style: "color: #3498db;" %>
              </div>
              <div class="card-text"><%= grant.user.name %></div>
              <div class="card-text"><%= grant.favorites.count %> 保存</div>
              <%= link_to admin_grant_path(grant) do %>
                <p class="card-text" style="color: #2980b9;">コメント件数：<%= grant.grant_comments.count %></p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= paginate @grants %>
 </div>

<%= render 'index', grants: @grants, grant_comments: @grant_comments %>

app/views/admin/grants/show.html.erb
<!DOCTYPE html>
  <title>補助金詳細</title>
  <link rel="stylesheet" type="text/css" href="/assets/application.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<body style="background-color: #e6f2f8;">
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-12 text-center mb-5">
        <h1 style="color: #3498db;">投稿詳細</h1>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-4 text-center my-3">
        <h4 style="color: #3498db;">タグ</h4>
        <p><% if @tag %><%= @tag.name %><% else %>タグなし<% end %></p>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-12 text-center my-3">
        <h4 style="color: #3498db;">補助金名</h4>
        <p><%= @grant.name %></p>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-12 text-center my-3">
        <h4 style="color: #3498db;">申請経緯</h4>
        <p><%= @grant.background %></p>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-12 text-center my-3">
        <h4 style="color: #3498db;">申請内容</h4>
        <p><%= @grant.body %></p>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-12 text-right my-3">
        <p style="color: #3498db;">コメント件数：<%= @grant.grant_comments.count %></p>
        <p style="color: #3498db;">いいね数：<%= @grant.favorites.count %> </p>
        <p>投稿者：<%= link_to @grant.user.name, admin_user_path(@grant.user.id), class: "text-decoration-none text-blue" %></p>
        <%= link_to "削除", admin_grant_path(@grant), method: :delete, class: 'btn btn-outline-danger', "data-confirm" => "本当に削除しますか？" %>
      </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-12 overflow-auto" style="max-width: 1200px; margin: 0 auto;">
        <% @grant.grant_comments.each do |grant_comment| %>
          <div class="row my-2 border-bottom">
            <div class="col-md-4 text-center">
              <p><%= grant_comment.user.name %></p>
            </div>
            <div class="col-md-4 align-items-center text-break">
             <p><%= grant_comment.created_at.strftime('%Y/%m/%d') %></p>
            <p class="<%= score_color_class(grant_comment.score) %> sentiment-score">
                本文の感情分析スコア[<%= grant_comment.score %>]</p>
             <p><%= grant_comment.comment %></p>
           </div>
            <div class="col-md-4 text-center d-flex align-items-center">
              <%= link_to "削除", admin_grant_grant_comment_path(grant_comment.grant, grant_comment), method: :delete, data: { confirm: "このコメントを削除しますか？" }, class: 'btn btn-md btn-danger text-white' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</body>