config/routes.rb
Rails.application.routes.draw do
  # 顧客用
# URL /users/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 # ゲストログイン
devise_scope :user do
      post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
                  end

namespace :admin do
    root to: "homes#top"
    resources :users
    resources :grants do
    resources :grant_comments, only: [:destroy]
   end
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
   end

 scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
      resources :users do
        collection do
          # 退会確認画面
          get  '/users/check' => 'users#check'
          # 論理削除用のルーティング
          patch  '/users/withdraw' => 'users#withdraw'
        end
      end
    resources :grants do
    resources :grant_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hojoraku2</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <script src="https://kit.fontawesome.com/4dbb6962d5.js" crossorigin="anonymous"></script>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>
<body>
  <header>
    <div>
      <h2><%= link_to 'hojoraku', root_path, class: "text-light text-decoration-none" %></h2>
    </div>

    <nav class="navbar-nav ml-auto">
      <div class="col-lg-4 d-flex justify-content-center">
        <%= render 'public/searches/search', grants: @grants, users: @users, tags: @tags %>
      </div>

        <ul class="navbar-nav ml-auto list-inline">
  <!-- 管理者がログインしている場合-->
  <% if admin_signed_in? %>
    <li class="d-inline-block">
      <%= link_to "会員一覧", admin_root_path, class: "text-light mx-2" %>
    </li>

    <li class="d-inline-block">
      <%= link_to "投稿一覧", admin_grants_path, data: {"turbolinks" => false}, class: "text-light mx-2" %>
    </li>

    <li class="d-inline-block">
      <%= link_to "タグ一覧", admin_tags_path, class: "text-light mx-2" %>
    </li>

    <li class="d-inline-block">
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "text-light mx-2" %>
    </li>

  <!-- ユーザー（会員）がログインしている場合 -->
  <% elsif user_signed_in? %>
    <li class="d-inline-block">
      <%= link_to "投稿一覧", grants_path, class: "text-light mx-2" %>
    </li>

    <li class="d-inline-block">
      <%= link_to "マイページ", user_path(current_user), class: "text-light mx-2" %>
    </li>

    <li class="d-inline-block">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-light mx-2" %>
    </li>

  <!-- ログインしていない場合 -->
  <% else %>
    <li class="d-inline-block">
      <%= link_to "投稿一覧", grants_path, class: "text-light mx-2" %>
    </li>

    <li class="d-inline-block">
      <%= link_to "新規登録", new_user_registration_path, class: "text-light mx-2" %>
    </li>

    <li class="d-inline-block">
      <%= link_to "ログイン(利用者)", new_user_session_path, class: "text-light mx-2" %>
    </li>

    <li class="d-inline-block">
      <%= link_to "ログイン(管理者)", new_admin_session_path, class: "text-light mx-2" %>
    </li>
  <% end %>
</ul>
    </nav>
  </header>

  <main style="border-bottom: 1px solid #ccc;">
  <%= yield %>
</main>

<footer style="background-color: #f0f6fa; border-top: 1px solid #ccc;">
  <div class="text-center py-2">
    <h4 class="logo"><%= link_to 'hojoraku', root_path, class: "text-black text-decoration-none" %></h4>
  </div>
</footer>
</body>
</html>